language: java
dist: trusty

jdk:
  - oraclejdk8

sudo:
  - required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS kiosk; CREATE DATABASE kiosk;' -uroot

install: true

script:
  - mvn clean install

after_success:
  - ./deploy_before.sh

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "io.tchepannou.kribi"
    skip_cleanup: true
    upload-dir: repository/kiosk-pipeline/$TRAVIS_COMMIT
    local_dir: target/deploy
    on:
      branch: master

after_deploy:
  - ./deploy_after.sh
