kiosk:
  environment: prod
  step:
    workers: 10
    prePublishMaxDurationSeconds: 1800  # 30 mins

  pipeline:
    reprocess: none
    maxThreadWait: 300000

spring:
  datasource:
    poolName: Kiosk.CP
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://kiosk.cwj11t2vidmo.us-east-1.rds.amazonaws.com:3306/kiosk
    username: kioskadmin
    password: kioskadmin

