kiosk:
  namespace: "io.tchepannou"
  aws:
    bucket: "${kiosk.namespace}.kiosk"

spring:
  http:
    multipart:
      max-file-size: 200000000  # 200Mb
      max-request-size: 200000000  # 200Mb

swagger:
  version: "1.0"
  title: Kiosk Processing Pipeline
  description: "Process Kiosk Messages"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  shutdown:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kiosk: INFO
    com.amazonaws: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level TransactionId=%X{TransactionId} Message='%m'%n"
    file: "%d Type=%level TransactionId=%X{TransactionId} Message='%m'%n"
