kiosk:
  namespace: "io.tchepannou"
  aws:
    s3:
      bucket: "${kiosk.namespace}.kiosk"

  pipeline:
    LoadFeedsProcessor:
      bucket: "${kiosk.aws.s3.bucket}"
      key: "${kiosk.environment}/feeds"
      outputQueue: "kiosk-${kiosk.environment}-feed-queue"

    UrlExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-feed-queue"
      outputQueue: "kiosk-${kiosk.environment}-url-queue"

    HtmlDownloadConsumer:
      inputQueue: "kiosk-${kiosk.environment}-url-queue"
      outputS3Bucket: "${kiosk.aws.s3.bucket}"
      outputS3Key: "${kiosk.environment}/html"
      outputTopic: "arn:aws:sns:us-east-1:828725992074:kiosk-dev-downloaded-topic"

    ContentExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-content-extraction-queue"
      htmlS3Key: "${kiosk.pipeline.HtmlDownloadConsumer.outputS3Key}"
      outputS3Bucket: "${kiosk.aws.s3.bucket}"
      outputS3Key: "${kiosk.environment}/content"

spring:
  datasource:
    poolName: Kiosk.CP
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/kiosk
    username: root
    #password:
    connectionTimeout: 30000
    connectionTestQuery: SELECT 1
    maximumPoolSize: 10
    idleTimeout: 15000
    maxLifetime: 60000
    leakDetectionThreshold: 30000
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048


swagger:
  version: "1.0"
  title: Kiosk Processing Pipeline
  description: "Process Kiosk Messages"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kiosk: INFO
    com.amazonaws: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level Thread=%thread Message='%m'%n"
    file: "%d Type=%level Thread=%thread Message='%m'%n"
