kiosk:
  namespace: "io.tchepannou"
  threadPool:
    size: 100
  pipeline:
    LoadFeedsProcessor:
      bucket: "${kiosk.namespace}.kiosk"
      key: "${kiosk.environment}/feeds"
      queue: "kiosk-${kiosk.environment}-feed"
    UrlExtractorProcessor:
      inputQueue: "kiosk-${kiosk.environment}-feed"
      outputQueue: "kiosk-${kiosk.environment}-url"
    HtmlDownloadProcessor:
      inputQueue: "kiosk-${kiosk.environment}-url"
      outputS3Bucket: "${kiosk.namespace}.kiosk"
      outputS3Key: "${kiosk.environment}/html/"


swagger:
  version: "1.0"
  title: Kiosk Processing Pipeline
  description: "Process Kiosk Messages"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kiosk: INFO
    com.amazonaws: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level Thread=%thread Message='%m'%n"
    file: "%d Type=%level Thread=%thread Message='%m'%n"
