kiosk:
  namespace: "io.tchepannou"
  aws:
    s3:
      s3Bucket: "${kiosk.namespace}.kiosk"

  pipeline:
    FeedProducer:
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"
      s3Key: "${kiosk.environment}/feeds"
      outputQueue: "kiosk-${kiosk.environment}-feed-queue"

    UrlExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-feed-queue"
      outputQueue: "kiosk-${kiosk.environment}-url-queue"

    HtmlDownloadConsumer:
      inputQueue: "kiosk-${kiosk.environment}-url-queue"
      outputTopic: "arn:aws:sns:us-east-1:828725992074:kiosk-${kiosk.environment}-downloaded-topic"
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"
      s3Key: "${kiosk.environment}/html"

    ContentExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-content-extraction-queue"
      outputQueue: "kiosk-${kiosk.environment}-matadata-extraction-queue"
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"
      s3Key: "${kiosk.environment}/content"
      s3KeyHtml: "${kiosk.pipeline.HtmlDownloadConsumer.s3Key}"

    MetadataExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-matadata-extraction-queue"
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"

    ImageExtractorConsumer:
      inputQueue: "kiosk-${kiosk.environment}-image-extraction-queue"
      outputQueue: "kiosk-${kiosk.environment}-thumbnail-generation-queue"
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"
      s3Key: "${kiosk.environment}/image"
      s3KeyHtml: "${kiosk.pipeline.HtmlDownloadConsumer.s3Key}"

    ImageThumbnailConsumer:
      inputQueue: "kiosk-${kiosk.environment}-thumbnail-generation-queue"
      s3Bucket: "${kiosk.aws.s3.s3Bucket}"
      s3Key: "${kiosk.environment}/image"
      thumbnailWidth: 144
      thumbnailHeight:  144


spring:
  datasource:
    poolName: Kiosk.CP
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/kiosk
    username: root
    #password:
    connectionTimeout: 30000
    connectionTestQuery: SELECT 1
    maximumPoolSize: 10
    idleTimeout: 15000
    maxLifetime: 60000
    leakDetectionThreshold: 30000
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048


swagger:
  version: "1.0"
  title: Kiosk Processing Pipeline
  description: "Process Kiosk Messages"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kiosk: INFO
    com.amazonaws: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level Thread=%thread Message='%m'%n"
    file: "%d Type=%level Thread=%thread Message='%m'%n"
