kiosk:
  namespace: "io.tchepannou"
  aws:
    s3:
      bucket: "${kiosk.namespace}.kiosk"
    sqs:
      feed: "kiosk-${kiosk.environment}-feed"
      url: "kiosk-${kiosk.environment}-url"

  pipeline:
    LoadFeedsProcessor:
      bucket: "${kiosk.namespace}.kiosk"
      key: "${kiosk.environment}/feeds"
      queue: "kiosk-${kiosk.environment}-feed"

    UrlExtractorConsumer:
      inputQueue: "${kiosk.aws.sqs.feed}"
      outputQueue: "${kiosk.aws.sqs.url}"
    HtmlDownloadConsumer:
      inputQueue: "${kiosk.aws.sqs.url}"
      outputS3Bucket: "${kiosk.namespace}.kiosk"
      outputS3Key: "${kiosk.environment}/html"


swagger:
  version: "1.0"
  title: Kiosk Processing Pipeline
  description: "Process Kiosk Messages"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kiosk: INFO
    com.amazonaws: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level Thread=%thread Message='%m'%n"
    file: "%d Type=%level Thread=%thread Message='%m'%n"
