ALTER TABLE feed MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE link MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE article MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE image MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
