ALTER TABLE feed MODIFY id BIGINT;

ALTER TABLE link MODIFY id BIGINT;
ALTER TABLE link MODIFY feed_fk BIGINT;

ALTER TABLE article MODIFY id BIGINT;
ALTER TABLE article MODIFY link_fk BIGINT;

ALTER TABLE image MODIFY id BIGINT;
ALTER TABLE image MODIFY link_fk BIGINT;
